#!/usr/bin/env node
/**
 * Validates commit messages against Conventional Commits 1.0.0.
 *
 * Zero dependencies, like everything else here - commitlint would mean a
 * dependency tree in a project whose whole pitch is not having one.
 *
 *   node tools/check-commits.mjs                 # validate HEAD
 *   node tools/check-commits.mjs <range>         # e.g. origin/main..HEAD
 *   node tools/check-commits.mjs --file <path>   # a commit-msg hook file
 *   node tools/check-commits.mjs --install-hook  # install the commit-msg hook
 *
 * Exit 0 if every message conforms, 1 otherwise.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, chmodSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Types allowed in this repository, per CONTRIBUTING.md. */
export const TYPES = [
  'feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test',
  'build', 'ci', 'chore', 'revert',
];

const MAX_SUBJECT = 72;

/**
 * @param {string} message full commit message
 * @returns {string[]} problems, empty when the message conforms
 */
export function validate(message) {
  const problems = [];
  const lines = message.replace(/\r\n/g, '\n').split('\n');

  // Comment lines exist in a commit-msg hook file; they are not part of the message.
  const meaningful = lines.filter((line) => !line.startsWith('#'));
  const subject = (meaningful[0] ?? '').trim();

  if (subject === '') return ['the commit message is empty'];

  // A merge or revert commit generated by git is exempt from the header shape.
  if (/^Merge /.test(subject)) return [];

  const header = /^(?<type>[a-z]+)(?:\((?<scope>[a-z0-9/_-]+)\))?(?<breaking>!)?: (?<description>.+)$/.exec(subject);
  if (!header) {
    problems.push(`subject must be "type(optional-scope): description" - got "${truncate(subject)}"`);
  } else {
    const { type, description } = header.groups;
    if (!TYPES.includes(type)) {
      problems.push(`"${type}" is not an allowed type. Use one of: ${TYPES.join(', ')}`);
    }
    if (/^[A-Z]/.test(description) && !/^[A-Z]{2,}/.test(description)) {
      problems.push('description should start lowercase (an acronym is fine)');
    }
    if (description.endsWith('.')) {
      problems.push('description should not end with a period');
    }
    if (subject.length > MAX_SUBJECT) {
      problems.push(`subject is ${subject.length} chars; keep it under ${MAX_SUBJECT}`);
    }
  }

  // Body, when present, must be separated from the subject by one blank line.
  if (meaningful.length > 1 && meaningful[1].trim() !== '') {
    problems.push('leave a blank line between the subject and the body');
  }

  // A breaking change needs either "!" in the header or a BREAKING CHANGE footer.
  const hasFooter = meaningful.some((line) => /^BREAKING[ -]CHANGE: /.test(line));
  if (hasFooter && header && !header.groups.breaking) {
    problems.push('a BREAKING CHANGE footer should be paired with "!" in the subject');
  }

  return problems;
}

const truncate = (text) => (text.length > 60 ? `${text.slice(0, 57)}...` : text);

const HOOK = `#!/bin/sh
# Installed by tools/check-commits.mjs - validates Conventional Commits.
exec node "$(git rev-parse --show-toplevel)/tools/check-commits.mjs" --file "$1"
`;

function installHook() {
  const hooksDir = execFileSync('git', ['rev-parse', '--git-path', 'hooks'], { encoding: 'utf8' }).trim();
  const absolute = hooksDir.startsWith('/') ? hooksDir : join(ROOT, hooksDir);
  if (!existsSync(absolute)) mkdirSync(absolute, { recursive: true });
  const target = join(absolute, 'commit-msg');
  writeFileSync(target, HOOK);
  chmodSync(target, 0o755);
  console.log(`Installed ${target}\nCommit messages are now validated locally.`);
  return 0;
}

function report(label, problems) {
  if (problems.length === 0) return false;
  console.error(`\n${label}`);
  for (const problem of problems) console.error(`  - ${problem}`);
  return true;
}

function main(argv) {
  if (argv.includes('--install-hook')) return installHook();

  const fileIndex = argv.indexOf('--file');
  if (fileIndex !== -1) {
    const path = argv[fileIndex + 1];
    if (!path) {
      console.error('--file requires a path');
      return 2;
    }
    const problems = validate(readFileSync(path, 'utf8'));
    if (report('Commit message does not follow Conventional Commits:', problems)) {
      console.error('\n  Format: type(optional-scope): description');
      console.error(`  Types:  ${TYPES.join(', ')}`);
      console.error('  Spec:   https://www.conventionalcommits.org/en/v1.0.0/\n');
      return 1;
    }
    return 0;
  }

  const range = argv.find((arg) => !arg.startsWith('-')) ?? '-1';
  const args = range === '-1' ? ['log', '-1', '--format=%H%x00%B%x1e'] : ['log', range, '--format=%H%x00%B%x1e'];
  let raw;
  try {
    raw = execFileSync('git', args, { encoding: 'utf8', cwd: ROOT });
  } catch {
    console.error(`Could not read commits for "${range}"`);
    return 2;
  }

  const commits = raw.split('\x1e').map((entry) => entry.trim()).filter(Boolean)
    .map((entry) => {
      const [sha, message] = entry.split('\x00');
      return { sha: sha.slice(0, 8), message };
    });

  let failed = false;
  for (const { sha, message } of commits) {
    const problems = validate(message);
    if (report(`${sha} ${truncate(message.split('\n')[0])}`, problems)) failed = true;
  }

  if (failed) {
    console.error(`\nSpec: https://www.conventionalcommits.org/en/v1.0.0/`);
    return 1;
  }
  console.log(`${commits.length} commit message${commits.length === 1 ? '' : 's'} conform to Conventional Commits.`);
  return 0;
}

// Only act as a CLI when invoked directly; the test suite imports validate().
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = main(process.argv.slice(2));
}
